### ISSUE TITLE
AccessDeniedException when starting on Windows with versions 2.x

### ISSUE THREAD

**Issue by anthonygerrard** [amirkibbar/bilberry#8]
The plugin won't start the server on Windows Vista / 7 on any 2.x version I've tried.  You get the following appearing in the log.

It does work on  Elasticsearch version 1.7.5.

`[2016-05-18 20:41:29,939][WARN ][bootstrap                ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: Access is denied
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:776)
    at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
    at com.sun.jna.Native.<clinit>(Native.java:131)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:260)
    at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:43)
    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:88)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:138)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2016-05-18 20:41:29,943][WARN ][bootstrap                ] cannot check if running as root because JNA is not available
[2016-05-18 20:41:29,944][WARN ][bootstrap                ] cannot register console handler because JNA is not available
[2016-05-18 20:41:29,945][WARN ][bootstrap                ] JNA not found. native methods and handlers will be disabled.
[2016-05-18 20:41:30,300][ERROR][bootstrap                ] Exception
java.nio.file.AccessDeniedException: C:\Windows\8729896591019777542.tmp
    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
    at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.createFile(Files.java:632)
    at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
    at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
    at java.nio.file.Files.createTempFile(Files.java:897)
    at org.elasticsearch.bootstrap.Security.selfTest(Security.java:233)
    at org.elasticsearch.bootstrap.Security.configure(Security.java:115)
    at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:181)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:159)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
`

**Comment by anthonygerrard** [comment]
I'm using gradle version 2.13, Java 1.8

**Comment by gesellix** [comment]
can you check if the config below helps?

```
    repositories {
        jcenter()
        maven { url 'http://dl.bintray.com/gesellix/gradle-plugins' }
    }
    dependencies {
        classpath "de.gesellix:gradle-elastic-plugin:0.0.12"
    }
```

That release is based on https://github.com/gesellix/bilberry/tree/fork which contains some Windows specific fixes.

**Comment by amirkibbar** [comment]
upgraded plugin to ES version 5, I guess version 2.x is not relevant anymore
